[package]
name = "runec"
version = "0.0.1"
edition = "2024"
rust-version = "1.95.0"
authors = ["Tyler Telis <xlitersps@gmail.com>"]
description = "A compiler for RuneScript, the scripting language used by RuneScape"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
ctor = "0.2"
lazy_static = "1.4"
