[package]
name = "rs-runec"
version = "0.1.2"
edition = "2024"
rust-version = "1.95.0"
authors = ["Tyler Telis <xlitersps@gmail.com>", "RustCityRS <https://github.com/RustCityRS>"]
description = "A RuneScript 2 Compiler and Linter Built Entirely in Rust"
license = "MIT"
repository = "https://github.com/RustCityRS/rs-compiler"
homepage = "https://github.com/RustCityRS/rs-compiler"
readme = "README.md"
include = ["src/**/*", "LICENSE.md", "README.md"]

[lib]
name = "runec"

[[bin]]
name = "runec"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
ctor = "0.2"
lazy_static = "1.4"
