[package]
name = "rs-compiler"
version.workspace = true
edition = "2024"
rust-version.workspace = true
authors = ["Tyler Telis <xlitersps@gmail.com>"]
description = "A compiler for RuneScript, the scripting language used by RuneScape"

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = "1.5"
tracing = { workspace = true }

# Internal crates - for definition loading and cache access
rs-cache = { workspace = true }

[dev-dependencies]
ctor = "0.2"
lazy_static = "1.4"
